id: 4a9f6ff2-73ae-47e1-a4ec-12d4d5fbbe9a
title: 2022-09-01-session
description: The party finally gets to the Bleeding Citadel
summary: Koshar gets burnt
image: https://dnd.sfo2.digitaloceanspaces.com/podcast-test/artifacts/art.jpg
releasedAt: 1662339408
season: 2
episodeNumber: 40
media:
  url: https://dnd.sfo2.digitaloceanspaces.com/podcast-test/artifacts/2022-09-01-session.mp3
  duration: 6305
  bytes: 100896867
keywords:
- Dungeons and Dragons
